# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\addDeck.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 143)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addDeckBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addDeckBtn.setFont(font)
        self.addDeckBtn.setIconSize(QtCore.QSize(20, 16))
        self.addDeckBtn.setObjectName("addDeckBtn")
        self.horizontalLayout.addWidget(self.addDeckBtn)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Enter deck name"))
        self.addDeckBtn.setText(_translate("Dialog", "Add"))
        self.cancelBtn.setText(_translate("Dialog", "Exit"))
