# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\playDeck.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 327)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.questionLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.questionLabel.setFont(font)
        self.questionLabel.setObjectName("questionLabel")
        self.verticalLayout.addWidget(self.questionLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.answerEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.answerEdit.setFont(font)
        self.answerEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.answerEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.answerEdit.setObjectName("answerEdit")
        self.verticalLayout.addWidget(self.answerEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.resultLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setAutoDefault(False)
        self.exitBtn.setDefault(False)
        self.exitBtn.setFlat(False)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        self.skipBtn = QtWidgets.QPushButton(Dialog)
        self.skipBtn.setAutoDefault(False)
        self.skipBtn.setObjectName("skipBtn")
        self.horizontalLayout.addWidget(self.skipBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.questionLabel.setText(_translate("Dialog", "TextLabel"))
        self.resultLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Press enter to begin</p></body></html>"))
        self.exitBtn.setText(_translate("Dialog", "Exit"))
        self.skipBtn.setText(_translate("Dialog", "Skip"))
