# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.allowed_errors = QtWidgets.QSpinBox(Dialog)
        self.allowed_errors.setMinimum(1)
        self.allowed_errors.setMaximum(300)
        self.allowed_errors.setObjectName("allowed_errors")
        self.gridLayout.addWidget(self.allowed_errors, 0, 1, 1, 1)
        self.error_limit = QtWidgets.QSpinBox(Dialog)
        self.error_limit.setObjectName("error_limit")
        self.gridLayout.addWidget(self.error_limit, 1, 1, 1, 1)
        self.perfect_time = QtWidgets.QSpinBox(Dialog)
        self.perfect_time.setObjectName("perfect_time")
        self.gridLayout.addWidget(self.perfect_time, 2, 1, 1, 1)
        self.incorrect_limit = QtWidgets.QSpinBox(Dialog)
        self.incorrect_limit.setObjectName("incorrect_limit")
        self.gridLayout.addWidget(self.incorrect_limit, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.applyBtn.setFont(font)
        self.applyBtn.setAutoDefault(False)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exitBtn.setFont(font)
        self.exitBtn.setAutoDefault(False)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setToolTip(_translate("Dialog", "<html><head/><body><p>This is the number of spelling mistakes you can make whilst still maintaining the ability to get a perfect score.</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Allowed spelling mistakes:</p></body></html>"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p>The number of spelling errors before your answer is marked as failed, moving onto the next card</p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Spelling error limit:</p></body></html>"))
        self.label_3.setToolTip(_translate("Dialog", "<html><head/><body><p>The number of seconds that you must answer within in order to obtain a perfect score</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Perfect score time limit (seconds):</p></body></html>"))
        self.label_4.setToolTip(_translate("Dialog", "<html><head/><body><p>The number of seconds that you have to answer the question before its marked as failed and the next card is drawn.</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Incorrect time limit (seconds):</p></body></html>"))
        self.applyBtn.setText(_translate("Dialog", "Apply Settings"))
        self.exitBtn.setText(_translate("Dialog", "Exit"))
